#!/bin/bash

# Script to make all repositories private
# Usage: ./make-private.sh

echo "Making all repositories private..."

# Array of all your repositories
repos=(
  "advice-api"
  "ai-summarizer-proxy"
  "antigravity-awesome-skills"
  "audiophile-ecommerce"
  "better-auth-crash-course"
  "bloocode-task-fe"
  "Bookmark-landingpage-fm"
  "Budget-app"
  "calculator"
  "calculator-fm"
  "chat-app"
  "cito"
  "clever-chat-relay"
  "Clinical-fe"
  "clinical-ui"
  "Countdown-timer"
  "crypto-dashboard"
  "csb-nk2zgr"
  "Currency-converter"
  "Deserts"
  "dev-jobs"
  "devfinder"
  "Dictionary-app"
  "dictionary-react"
  "DSI_SPORTS"
  "E-commerce"
  "E-shopping"
  "E-wears"
  "entertainment-web-app"
  "everything-claude-code"
  "first-contributions"
  "fm-tipCalculator"
  "form-validation-fm"
  "freelance-portfolio"
  "Frontend-quiz-app"
  "fx-checker-native"
  "Github-User-and-Advice-"
  "Github-user-search"
  "hng-14-mobile-stage1"
  "hng-14-stage-zero"
  "HNG-frontend-stage0"
  "hng-stage-5b"
  "hng12-stage2-Conference-ticket-generator"
  "hng12-stage3-AI-text-processing-interface"
  "hng14-stage-1b"
  "hng14-stage2-frontend-invoice"
  "hng14-stage3-frontend"
  "hng14-stage4a-frontend"
  "Invoice-app"
  "Invoicely"
  "invoicely-app"
  "ip-address-tracker"
  "javascript-testing-starter"
  "jemmycodes"
  "job-filtering"
  "Kanban"
  "learning-github"
  "Lumina-customer-support--agent"
  "mastering_git"
  "Meme-generator"
  "mobile-nav"
  "Movie-app"
  "mum-mentor-FE"
  "mum-mentor-mobile"
  "n8n-mcp"
  "n8n-workflow-backups"
  "New-Quiz-App"
  "nextjs-dashboard"
  "nextjs_unit_test"
  "nosa-portfolio"
  "notenest_note-taking-app"
  "Notes-app"
  "notificationPage--FM"
  "Ox-rollup"
  "Personal-finance-app"
  "Pomodoro-timer"
  "Portfolio"
  "Portfolio-website"
  "project-assignment"
  "projectmate"
  "prompt-eng-interactive-tutorial"
  "Query-builder"
  "quran-database"
  "Recipe-finder"
  "Rest-Countries"
  "Ridwan-Lawal"
  "Rock-paper-scissors"
  "shopping-cart"
  "Shopping-carts"
  "shortly-react-app"
  "signup-page"
  "skills-introduction-to-git"
  "skills-introduction-to-github"
  "skills-introduction-to-repository-management"
  "stage1-guess-the-color-Ibn"
)

count=0
failed=0

for repo in "${repos[@]}"; do
  echo "Processing: $repo"
  if gh repo edit Ridwan-Lawal/$repo --visibility private 2>/dev/null; then
    ((count++))
    echo "✓ $repo is now private"
  else
    ((failed++))
    echo "✗ Failed to make $repo private"
  fi
done

echo ""
echo "========================================="
echo "Summary:"
echo "Successfully made private: $count"
echo "Failed: $failed"
echo "========================================="
